# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naveen M V
email: naveenmv7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is made by Naveen M V. It consists of his ideas, works and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naveenmv.com" # the base hostname & protocol for your site
twitter_username: IamNaveenMV
github_username:  Naveen97

# Build settings
markdown: kramdown
